/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseCourseIdRouteImport } from './routes/course.$courseId'
import { Route as BranchBranchIdRouteImport } from './routes/branch.$branchId'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchBranchIdRoute = BranchBranchIdRouteImport.update({
  id: '/branch/$branchId',
  path: '/branch/$branchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/resources': typeof ResourcesRoute
  '/workspace': typeof WorkspaceRoute
  '/branch/$branchId': typeof BranchBranchIdRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/resources': typeof ResourcesRoute
  '/workspace': typeof WorkspaceRoute
  '/branch/$branchId': typeof BranchBranchIdRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/resources': typeof ResourcesRoute
  '/workspace': typeof WorkspaceRoute
  '/branch/$branchId': typeof BranchBranchIdRoute
  '/course/$courseId': typeof CourseCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branches'
    | '/resources'
    | '/workspace'
    | '/branch/$branchId'
    | '/course/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branches'
    | '/resources'
    | '/workspace'
    | '/branch/$branchId'
    | '/course/$courseId'
  id:
    | '__root__'
    | '/'
    | '/branches'
    | '/resources'
    | '/workspace'
    | '/branch/$branchId'
    | '/course/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BranchesRoute: typeof BranchesRoute
  ResourcesRoute: typeof ResourcesRoute
  WorkspaceRoute: typeof WorkspaceRoute
  BranchBranchIdRoute: typeof BranchBranchIdRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/$branchId': {
      id: '/branch/$branchId'
      path: '/branch/$branchId'
      fullPath: '/branch/$branchId'
      preLoaderRoute: typeof BranchBranchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BranchesRoute: BranchesRoute,
  ResourcesRoute: ResourcesRoute,
  WorkspaceRoute: WorkspaceRoute,
  BranchBranchIdRoute: BranchBranchIdRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
